import { localTourSchema, type LocalTour } from '@clik2trip/contracts';

/**
 * The demonstration catalog: authored sample inventory used to exercise the
 * local recommendation path where the connected Clik2Trip catalog is still
 * small, and to give a measurement run enough entries for retrieval to mean
 * something.
 *
 * Provenance, stated once and enforced by `source: 'demo-seed'` on every entry:
 * these descriptions are written for this repository. They describe activities
 * that genuinely exist at these coordinates, but no text, photograph, price or
 * record was copied from any booking platform, and no such platform's site was
 * crawled to build this file. Nothing here is bookable inventory — every entry
 * settles through the demonstration path, which never touches the Clik2Trip
 * Gateway and never creates a real booking.
 *
 * `priceFrom` is a plausible reference figure for the kind of activity, not a
 * quote from an operator. It exists so the demonstration checkout has a total
 * to freeze; the testnet transfer itself uses the sandbox tariff.
 */

const demoCurrency = 'USD';

interface DemoSeed {
  slug: string;
  title: string;
  summary: string;
  destinationName: string;
  regionId: string;
  categoryName: string;
  durationMin: number;
  priceFrom: number;
  providerName: string;
  lat: number;
  lng: number;
  includes: string[];
  excludes: string[];
  searchTerms: string[];
}

const seeds: DemoSeed[] = [
  // ---------------------------------------------------------------- Panama City
  {
    slug: 'isla-otoque-dia-completo',
    title: 'Isla Otoque día completo con almuerzo local',
    summary:
      'Travesía por el golfo hasta una isla de pescadores, con tiempo de playa, snorkel y almuerzo preparado en la comunidad.',
    destinationName: 'Isla Otoque',
    regionId: 'panama-city',
    categoryName: 'Islas',
    durationMin: 540,
    priceFrom: 95,
    providerName: 'Operador demo Pacífico',
    lat: 8.6333,
    lng: -79.6167,
    includes: ['Transporte marítimo', 'Almuerzo local', 'Equipo de snorkel', 'Guía bilingüe'],
    excludes: ['Bebidas alcohólicas', 'Propinas'],
    searchTerms: [
      'island',
      'boat',
      'beach',
      'snorkel',
      'ocean',
      'fishing village',
      'isla',
      'lancha',
      'playa',
      'golfo',
    ],
  },
  {
    slug: 'casco-viejo-a-pie',
    title: 'Casco Viejo a pie',
    summary:
      'Recorrido por las plazas, iglesias y balcones del centro histórico, terminando en el paseo frente a la bahía.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Cultura',
    durationMin: 180,
    priceFrom: 35,
    providerName: 'Operador demo Ciudad',
    lat: 8.9506,
    lng: -79.535,
    includes: ['Guía de historia local', 'Agua embotellada'],
    excludes: ['Transporte al punto de encuentro', 'Comidas'],
    searchTerms: [
      'colonial',
      'architecture',
      'historic',
      'plaza',
      'church',
      'old town',
      'street',
      'casco antiguo',
      'histórico',
      'arquitectura',
    ],
  },
  {
    slug: 'canal-esclusas-miraflores',
    title: 'Canal de Panamá: esclusas de Miraflores',
    summary:
      'Visita a las terrazas de observación para ver el paso de buques por las esclusas, con museo y sala de proyección.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Cultura',
    durationMin: 240,
    priceFrom: 60,
    providerName: 'Operador demo Ciudad',
    lat: 8.9986,
    lng: -79.5906,
    includes: ['Entrada al centro de visitantes', 'Transporte ida y vuelta', 'Guía'],
    excludes: ['Almuerzo', 'Propinas'],
    searchTerms: [
      'canal',
      'locks',
      'ship',
      'engineering',
      'museum',
      'water',
      'esclusas',
      'buque',
      'ingeniería',
    ],
  },
  {
    slug: 'transito-parcial-canal',
    title: 'Tránsito parcial por el Canal de Panamá',
    summary:
      'Navegación a bordo de un barco de pasajeros cruzando esclusas y el corte Culebra, con narración durante el trayecto.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Navegación',
    durationMin: 300,
    priceFrom: 185,
    providerName: 'Operador demo Ciudad',
    lat: 8.95,
    lng: -79.56,
    includes: ['Embarque', 'Almuerzo a bordo', 'Narración en vivo'],
    excludes: ['Traslado al muelle', 'Bebidas'],
    searchTerms: [
      'canal',
      'boat',
      'cruise',
      'locks',
      'transit',
      'river',
      'navegación',
      'crucero',
      'tránsito',
    ],
  },
  {
    slug: 'isla-taboga-dia-completo',
    title: 'Isla Taboga día completo',
    summary:
      'Ferry a la isla de las flores, con playa, calles empinadas y vistas del skyline al regreso.',
    destinationName: 'Isla Taboga',
    regionId: 'panama-city',
    categoryName: 'Playa y mar',
    durationMin: 480,
    priceFrom: 75,
    providerName: 'Operador demo Pacífico',
    lat: 8.7997,
    lng: -79.5556,
    includes: ['Ferry ida y vuelta', 'Tasa de entrada a la isla', 'Silla de playa'],
    excludes: ['Comidas', 'Actividades acuáticas'],
    searchTerms: [
      'island',
      'ferry',
      'beach',
      'ocean',
      'swimming',
      'coastal',
      'isla',
      'playa',
      'mar',
    ],
  },
  {
    slug: 'parque-metropolitano-caminata',
    title: 'Caminata en el Parque Natural Metropolitano',
    summary:
      'Sendero de bosque tropical dentro de la ciudad, con mirador sobre el skyline y avistamiento de perezosos y tucanes.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Naturaleza',
    durationMin: 150,
    priceFrom: 30,
    providerName: 'Operador demo Ciudad',
    lat: 8.993,
    lng: -79.543,
    includes: ['Entrada al parque', 'Guía naturalista', 'Binoculares compartidos'],
    excludes: ['Transporte', 'Repelente'],
    searchTerms: [
      'forest',
      'trail',
      'hiking',
      'wildlife',
      'birds',
      'jungle',
      'nature',
      'bosque',
      'sendero',
      'naturaleza',
    ],
  },
  {
    slug: 'monkey-island-lago-gatun',
    title: 'Monkey Island y Lago Gatún',
    summary:
      'Paseo en lancha por las islas del lago artificial del Canal, con avistamiento de monos, perezosos y aves acuáticas.',
    destinationName: 'Lago Gatún',
    regionId: 'panama-city',
    categoryName: 'Naturaleza',
    durationMin: 420,
    priceFrom: 110,
    providerName: 'Operador demo Ciudad',
    lat: 9.12,
    lng: -79.75,
    includes: ['Transporte', 'Paseo en lancha', 'Guía naturalista', 'Refrigerio'],
    excludes: ['Almuerzo completo', 'Propinas'],
    searchTerms: [
      'lake',
      'monkey',
      'wildlife',
      'boat',
      'jungle',
      'rainforest',
      'birds',
      'lago',
      'monos',
      'selva',
    ],
  },
  {
    slug: 'panama-viejo-museo',
    title: 'Panamá Viejo y su museo',
    summary:
      'Ruinas de la primera ciudad del Pacífico, con la torre de la catedral y el museo de sitio.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Cultura',
    durationMin: 180,
    priceFrom: 28,
    providerName: 'Operador demo Ciudad',
    lat: 9.0075,
    lng: -79.4842,
    includes: ['Entrada al conjunto monumental', 'Guía de historia'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'ruins',
      'historic',
      'museum',
      'stone',
      'tower',
      'archaeology',
      'ruinas',
      'histórico',
      'museo',
    ],
  },
  {
    slug: 'mercado-mariscos-sabores',
    title: 'Mercado de mariscos y sabores de la ciudad',
    summary:
      'Ruta de degustación por el mercado y las fondas del centro, con ceviche, frituras y sobremesa.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Gastronomía',
    durationMin: 210,
    priceFrom: 55,
    providerName: 'Operador demo Ciudad',
    lat: 8.952,
    lng: -79.531,
    includes: ['Todas las degustaciones', 'Guía gastronómico'],
    excludes: ['Bebidas adicionales', 'Transporte'],
    searchTerms: [
      'food',
      'market',
      'seafood',
      'tasting',
      'ceviche',
      'local cuisine',
      'comida',
      'mercado',
      'gastronomía',
    ],
  },
  {
    slug: 'amador-velero-atardecer',
    title: 'Velero al atardecer por la bahía de Amador',
    summary:
      'Salida en velero desde la calzada con el skyline y el puente de las Américas de fondo, al caer el sol.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Navegación',
    durationMin: 180,
    priceFrom: 70,
    providerName: 'Operador demo Pacífico',
    lat: 8.917,
    lng: -79.529,
    includes: ['Navegación en velero', 'Bebida de bienvenida', 'Chaleco salvavidas'],
    excludes: ['Cena', 'Transporte al muelle'],
    searchTerms: [
      'sailing',
      'sunset',
      'boat',
      'skyline',
      'bay',
      'ocean',
      'velero',
      'atardecer',
      'bahía',
    ],
  },
  {
    slug: 'biomuseo-calzada-bici',
    title: 'Biomuseo y Calzada de Amador en bicicleta',
    summary:
      'Pedaleo por la calzada que une las islas del Pacífico, con parada en el museo de biodiversidad.',
    destinationName: 'Ciudad de Panamá',
    regionId: 'panama-city',
    categoryName: 'Cultura',
    durationMin: 180,
    priceFrom: 40,
    providerName: 'Operador demo Ciudad',
    lat: 8.933,
    lng: -79.533,
    includes: ['Alquiler de bicicleta', 'Casco', 'Entrada al museo'],
    excludes: ['Comidas', 'Transporte'],
    searchTerms: [
      'cycling',
      'bike',
      'museum',
      'causeway',
      'architecture',
      'waterfront',
      'bicicleta',
      'museo',
      'calzada',
    ],
  },

  // --------------------------------------------------------------- Panamá Oeste
  {
    slug: 'kitesurf-punta-chame',
    title: 'Kitesurf en Punta Chame para principiantes',
    summary:
      'Clase inicial en la península de viento constante y agua poco profunda, con instructor certificado.',
    destinationName: 'Punta Chame',
    regionId: 'panama-oeste',
    categoryName: 'Playa y mar',
    durationMin: 240,
    priceFrom: 120,
    providerName: 'Operador demo Pacífico',
    lat: 8.647,
    lng: -79.7,
    includes: ['Equipo completo de kite', 'Instructor certificado', 'Seguro de actividad'],
    excludes: ['Transporte', 'Almuerzo'],
    searchTerms: [
      'kitesurf',
      'kiteboarding',
      'wind',
      'beach',
      'water sports',
      'ocean',
      'waves',
      'viento',
      'playa',
      'deporte acuático',
    ],
  },
  {
    slug: 'ballenas-punta-chame',
    title: 'Avistamiento de ballenas desde Punta Chame',
    summary:
      'Salida en lancha durante la temporada de jorobadas, con avistamiento a distancia responsable.',
    destinationName: 'Punta Chame',
    regionId: 'panama-oeste',
    categoryName: 'Naturaleza',
    durationMin: 300,
    priceFrom: 95,
    providerName: 'Operador demo Pacífico',
    lat: 8.647,
    lng: -79.7,
    includes: ['Paseo en lancha', 'Guía marino', 'Chaleco salvavidas', 'Refrigerio'],
    excludes: ['Transporte terrestre', 'Propinas'],
    searchTerms: [
      'whale',
      'wildlife',
      'boat',
      'ocean',
      'marine',
      'nature',
      'ballenas',
      'avistamiento',
      'mar',
    ],
  },
  {
    slug: 'cabalgata-playa-coronado',
    title: 'Cabalgata por la playa de Coronado',
    summary: 'Paseo a caballo por la arena oscura de Coronado, apto para jinetes sin experiencia.',
    destinationName: 'Coronado',
    regionId: 'panama-oeste',
    categoryName: 'Aventura',
    durationMin: 120,
    priceFrom: 65,
    providerName: 'Operador demo Pacífico',
    lat: 8.533,
    lng: -79.95,
    includes: ['Caballo y montura', 'Casco', 'Guía ecuestre'],
    excludes: ['Transporte', 'Fotografías'],
    searchTerms: [
      'horse',
      'riding',
      'beach',
      'sand',
      'coastal',
      'animals',
      'caballo',
      'cabalgata',
      'playa',
    ],
  },
  {
    slug: 'surf-playa-malibu',
    title: 'Surf para principiantes en Playa Malibú',
    summary: 'Dos horas de clase en una playa de olas suaves, con teoría en arena y práctica guiada.',
    destinationName: 'Gorgona',
    regionId: 'panama-oeste',
    categoryName: 'Playa y mar',
    durationMin: 180,
    priceFrom: 55,
    providerName: 'Operador demo Pacífico',
    lat: 8.556,
    lng: -79.92,
    includes: ['Tabla de surf', 'Licra', 'Instructor certificado'],
    excludes: ['Transporte', 'Bloqueador solar'],
    searchTerms: [
      'surf',
      'surfing',
      'waves',
      'beach',
      'ocean',
      'beginner',
      'board',
      'olas',
      'playa',
      'tabla',
    ],
  },
  {
    slug: 'manglares-chame-kayak',
    title: 'Manglares de Chame en kayak',
    summary:
      'Remada tranquila entre canales de manglar, con parada para observar aves zancudas y cangrejos.',
    destinationName: 'Chame',
    regionId: 'panama-oeste',
    categoryName: 'Naturaleza',
    durationMin: 210,
    priceFrom: 60,
    providerName: 'Operador demo Pacífico',
    lat: 8.63,
    lng: -79.73,
    includes: ['Kayak y remo', 'Chaleco salvavidas', 'Guía naturalista'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'kayak',
      'mangrove',
      'paddling',
      'birds',
      'water',
      'nature',
      'wetland',
      'manglar',
      'remo',
      'aves',
    ],
  },
  {
    slug: 'isla-taborcillo-desde-chame',
    title: 'Isla Taborcillo desde Punta Chame',
    summary: 'Cruce corto a una isla pequeña frente a la costa, con playa, senderos y almuerzo.',
    destinationName: 'Isla Taborcillo',
    regionId: 'panama-oeste',
    categoryName: 'Islas',
    durationMin: 360,
    priceFrom: 85,
    providerName: 'Operador demo Pacífico',
    lat: 8.6,
    lng: -79.78,
    includes: ['Transporte marítimo', 'Almuerzo', 'Acceso a la isla'],
    excludes: ['Bebidas', 'Transporte terrestre'],
    searchTerms: [
      'island',
      'boat',
      'beach',
      'day trip',
      'ocean',
      'coastal',
      'isla',
      'playa',
      'lancha',
    ],
  },

  // --------------------------------------------------------------------- Coclé
  {
    slug: 'el-valle-anton-dia-completo',
    title: 'El Valle de Antón día completo',
    summary:
      'Subida al pueblo dentro de un cráter volcánico, con mercado artesanal, mirador y bosque nuboso.',
    destinationName: 'El Valle de Antón',
    regionId: 'cocle',
    categoryName: 'Naturaleza',
    durationMin: 480,
    priceFrom: 90,
    providerName: 'Operador demo Coclé',
    lat: 8.603,
    lng: -80.127,
    includes: ['Transporte', 'Guía', 'Entradas', 'Almuerzo'],
    excludes: ['Compras en el mercado', 'Propinas'],
    searchTerms: [
      'volcano',
      'crater',
      'mountain',
      'forest',
      'market',
      'village',
      'nature',
      'valle',
      'cráter',
      'montaña',
    ],
  },
  {
    slug: 'chorro-el-macho-ranas-doradas',
    title: 'Chorro El Macho y sendero de las ranas doradas',
    summary:
      'Cascada de treinta y cinco metros y un sendero corto donde se conserva la rana dorada panameña.',
    destinationName: 'El Valle de Antón',
    regionId: 'cocle',
    categoryName: 'Naturaleza',
    durationMin: 180,
    priceFrom: 35,
    providerName: 'Operador demo Coclé',
    lat: 8.61,
    lng: -80.14,
    includes: ['Entrada a la reserva', 'Guía naturalista'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'waterfall',
      'forest',
      'trail',
      'frog',
      'wildlife',
      'river',
      'nature',
      'cascada',
      'sendero',
      'bosque',
    ],
  },
  {
    slug: 'canopy-el-valle',
    title: 'Canopy sobre el bosque nuboso de El Valle',
    summary: 'Circuito de cables sobre el dosel y una cascada, con arneses y briefing de seguridad.',
    destinationName: 'El Valle de Antón',
    regionId: 'cocle',
    categoryName: 'Aventura',
    durationMin: 150,
    priceFrom: 70,
    providerName: 'Operador demo Coclé',
    lat: 8.612,
    lng: -80.135,
    includes: ['Equipo de arnés', 'Guías de seguridad', 'Seguro de actividad'],
    excludes: ['Transporte', 'Fotografías'],
    searchTerms: [
      'zipline',
      'canopy',
      'adventure',
      'forest',
      'height',
      'jungle',
      'adrenaline',
      'tirolina',
      'aventura',
      'dosel',
    ],
  },
  {
    slug: 'termales-barro-el-valle',
    title: 'Aguas termales y baños de barro de El Valle',
    summary: 'Pozas termales de origen volcánico con mascarilla de barro y zona de descanso.',
    destinationName: 'El Valle de Antón',
    regionId: 'cocle',
    categoryName: 'Bienestar',
    durationMin: 120,
    priceFrom: 25,
    providerName: 'Operador demo Coclé',
    lat: 8.604,
    lng: -80.123,
    includes: ['Acceso a las pozas', 'Barro mineral', 'Casillero'],
    excludes: ['Toalla', 'Transporte'],
    searchTerms: [
      'hot springs',
      'thermal',
      'wellness',
      'spa',
      'relaxation',
      'volcanic',
      'mud',
      'termales',
      'bienestar',
      'barro',
    ],
  },
  {
    slug: 'india-dormida-amanecer',
    title: 'Cerro La India Dormida al amanecer',
    summary:
      'Ascenso temprano por la silueta que domina el valle, con petroglifos en el camino y vista al cráter.',
    destinationName: 'El Valle de Antón',
    regionId: 'cocle',
    categoryName: 'Senderismo',
    durationMin: 240,
    priceFrom: 45,
    providerName: 'Operador demo Coclé',
    lat: 8.618,
    lng: -80.145,
    includes: ['Guía de montaña', 'Agua', 'Fruta'],
    excludes: ['Transporte', 'Bastones de trekking'],
    searchTerms: [
      'hiking',
      'sunrise',
      'mountain',
      'trail',
      'viewpoint',
      'summit',
      'rocks',
      'senderismo',
      'amanecer',
      'cerro',
    ],
  },
  {
    slug: 'playa-blanca-catamaran',
    title: 'Playa Blanca y Farallón en catamarán',
    summary: 'Navegación costera con parada de baño y snorkel, y arena clara en la bajada del sol.',
    destinationName: 'Farallón',
    regionId: 'cocle',
    categoryName: 'Playa y mar',
    durationMin: 300,
    priceFrom: 105,
    providerName: 'Operador demo Coclé',
    lat: 8.38,
    lng: -80.16,
    includes: ['Catamarán', 'Equipo de snorkel', 'Refrigerio', 'Bebidas sin alcohol'],
    excludes: ['Transporte terrestre', 'Propinas'],
    searchTerms: [
      'catamaran',
      'sailing',
      'beach',
      'snorkel',
      'ocean',
      'white sand',
      'boat',
      'catamarán',
      'playa',
      'navegación',
    ],
  },

  // --------------------------------------------------------------------- Colón
  {
    slug: 'portobelo-fuertes-bahia',
    title: 'Portobelo: fuertes coloniales y bahía',
    summary:
      'Baterías españolas frente a la bahía, la iglesia del Cristo Negro y el puerto donde salía la plata del virreinato.',
    destinationName: 'Portobelo',
    regionId: 'colon',
    categoryName: 'Cultura',
    durationMin: 360,
    priceFrom: 80,
    providerName: 'Operador demo Caribe',
    lat: 9.553,
    lng: -79.656,
    includes: ['Transporte', 'Guía de historia', 'Entradas'],
    excludes: ['Almuerzo', 'Propinas'],
    searchTerms: [
      'fort',
      'colonial',
      'historic',
      'bay',
      'stone',
      'church',
      'caribbean',
      'fuerte',
      'colonial',
      'bahía',
    ],
  },
  {
    slug: 'esclusas-agua-clara',
    title: 'Esclusas de Agua Clara y la ampliación del Canal',
    summary:
      'Mirador sobre las esclusas nuevas del lado Caribe, con el lago Gatún al fondo y sala de exhibición.',
    destinationName: 'Colón',
    regionId: 'colon',
    categoryName: 'Cultura',
    durationMin: 300,
    priceFrom: 75,
    providerName: 'Operador demo Caribe',
    lat: 9.27,
    lng: -79.82,
    includes: ['Entrada al centro de visitantes', 'Transporte', 'Guía'],
    excludes: ['Comidas', 'Propinas'],
    searchTerms: [
      'canal',
      'locks',
      'ship',
      'engineering',
      'lake',
      'viewpoint',
      'esclusas',
      'canal',
      'mirador',
    ],
  },
  {
    slug: 'isla-grande-snorkel',
    title: 'Isla Grande: snorkel y playa',
    summary: 'Cruce corto desde La Guaira a una isla caribeña con arrecife somero y cocoteros.',
    destinationName: 'Isla Grande',
    regionId: 'colon',
    categoryName: 'Playa y mar',
    durationMin: 480,
    priceFrom: 95,
    providerName: 'Operador demo Caribe',
    lat: 9.628,
    lng: -79.572,
    includes: ['Transporte marítimo', 'Equipo de snorkel', 'Almuerzo'],
    excludes: ['Bebidas alcohólicas', 'Transporte terrestre'],
    searchTerms: [
      'island',
      'snorkel',
      'reef',
      'beach',
      'caribbean',
      'palm',
      'ocean',
      'isla',
      'arrecife',
      'playa',
    ],
  },
  {
    slug: 'fuerte-san-lorenzo',
    title: 'Fuerte San Lorenzo y el Camino de Cruces',
    summary:
      'Fortaleza sobre el acantilado en la desembocadura del Chagres, con tramo de bosque protegido.',
    destinationName: 'Colón',
    regionId: 'colon',
    categoryName: 'Cultura',
    durationMin: 300,
    priceFrom: 70,
    providerName: 'Operador demo Caribe',
    lat: 9.3,
    lng: -79.98,
    includes: ['Transporte', 'Guía', 'Entradas'],
    excludes: ['Almuerzo', 'Repelente'],
    searchTerms: [
      'fort',
      'ruins',
      'cliff',
      'river',
      'historic',
      'forest',
      'stone',
      'fuerte',
      'ruinas',
      'acantilado',
    ],
  },
  {
    slug: 'kayak-manglares-portobelo',
    title: 'Kayak entre los manglares de Portobelo',
    summary: 'Remada por ensenadas protegidas del Caribe, con parada de baño en aguas calmadas.',
    destinationName: 'Portobelo',
    regionId: 'colon',
    categoryName: 'Naturaleza',
    durationMin: 180,
    priceFrom: 50,
    providerName: 'Operador demo Caribe',
    lat: 9.55,
    lng: -79.66,
    includes: ['Kayak y remo', 'Chaleco salvavidas', 'Guía'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'kayak',
      'mangrove',
      'paddling',
      'bay',
      'water',
      'caribbean',
      'nature',
      'manglar',
      'kayak',
      'bahía',
    ],
  },

  // ----------------------------------------------------------------- Guna Yala
  {
    slug: 'san-blas-tres-islas',
    title: 'San Blas: tres islas y snorkel',
    summary:
      'Día completo en el archipiélago guna, con piscina natural, arrecife y almuerzo de pescado en la isla.',
    destinationName: 'Guna Yala',
    regionId: 'guna-yala',
    categoryName: 'Islas',
    durationMin: 720,
    priceFrom: 145,
    providerName: 'Operador demo Caribe',
    lat: 9.57,
    lng: -78.95,
    includes: ['Transporte 4x4', 'Lancha entre islas', 'Almuerzo', 'Tasas comunitarias'],
    excludes: ['Bebidas', 'Propinas', 'Equipo de snorkel propio'],
    searchTerms: [
      'island',
      'caribbean',
      'snorkel',
      'reef',
      'turquoise',
      'sandbar',
      'boat',
      'archipiélago',
      'isla',
      'arrecife',
    ],
  },
  {
    slug: 'cayos-holandeses-dos-dias',
    title: 'Cayos Holandeses en velero, dos días',
    summary:
      'Travesía con noche a bordo entre cayos de arrecife exterior, con snorkel en el naufragio y cena a bordo.',
    destinationName: 'Guna Yala',
    regionId: 'guna-yala',
    categoryName: 'Navegación',
    durationMin: 2880,
    priceFrom: 390,
    providerName: 'Operador demo Caribe',
    lat: 9.6,
    lng: -78.7,
    includes: ['Camarote compartido', 'Todas las comidas', 'Equipo de snorkel', 'Tasas'],
    excludes: ['Transporte al puerto', 'Bebidas alcohólicas'],
    searchTerms: [
      'sailing',
      'boat',
      'overnight',
      'reef',
      'snorkel',
      'caribbean',
      'shipwreck',
      'velero',
      'cayos',
      'navegación',
    ],
  },
  {
    slug: 'cultura-guna-carti',
    title: 'Cultura guna en Cartí',
    summary:
      'Visita a una comunidad isleña con museo local, molas y explicación de su gobierno autónomo.',
    destinationName: 'Cartí',
    regionId: 'guna-yala',
    categoryName: 'Cultura',
    durationMin: 360,
    priceFrom: 110,
    providerName: 'Operador demo Caribe',
    lat: 9.46,
    lng: -78.96,
    includes: ['Transporte', 'Tasas comunitarias', 'Guía local guna'],
    excludes: ['Compra de artesanía', 'Comidas'],
    searchTerms: [
      'culture',
      'indigenous',
      'community',
      'textile',
      'island',
      'museum',
      'tradition',
      'cultura',
      'comunidad',
      'artesanía',
    ],
  },
  {
    slug: 'isla-perro-naufragio',
    title: 'Isla Perro y el naufragio en snorkel',
    summary:
      'Isla pequeña con un casco hundido a pocos metros de la orilla, accesible con máscara y tubo.',
    destinationName: 'Guna Yala',
    regionId: 'guna-yala',
    categoryName: 'Playa y mar',
    durationMin: 480,
    priceFrom: 130,
    providerName: 'Operador demo Caribe',
    lat: 9.58,
    lng: -78.83,
    includes: ['Lancha', 'Equipo de snorkel', 'Almuerzo', 'Tasas comunitarias'],
    excludes: ['Transporte terrestre', 'Bebidas'],
    searchTerms: [
      'snorkel',
      'shipwreck',
      'island',
      'reef',
      'caribbean',
      'swimming',
      'clear water',
      'naufragio',
      'snorkel',
      'isla',
    ],
  },

  // ------------------------------------------------------------------ Chiriquí
  {
    slug: 'boquete-fincas-cafe',
    title: 'Boquete: fincas de café y cata',
    summary:
      'Recorrido por un beneficio de altura, del grano al tueste, terminando en una cata guiada de geisha.',
    destinationName: 'Boquete',
    regionId: 'chiriqui',
    categoryName: 'Gastronomía',
    durationMin: 240,
    priceFrom: 45,
    providerName: 'Operador demo Chiriquí',
    lat: 8.78,
    lng: -82.44,
    includes: ['Visita a la finca', 'Cata de café', 'Guía'],
    excludes: ['Transporte', 'Compra de café'],
    searchTerms: [
      'coffee',
      'farm',
      'tasting',
      'plantation',
      'mountain',
      'agriculture',
      'café',
      'finca',
      'cata',
    ],
  },
  {
    slug: 'sendero-los-quetzales',
    title: 'Sendero Los Quetzales',
    summary:
      'Travesía de bosque nuboso entre Boquete y Cerro Punta, con río, puentes y avistamiento de quetzales en temporada.',
    destinationName: 'Boquete',
    regionId: 'chiriqui',
    categoryName: 'Senderismo',
    durationMin: 420,
    priceFrom: 75,
    providerName: 'Operador demo Chiriquí',
    lat: 8.83,
    lng: -82.55,
    includes: ['Guía de montaña', 'Entrada al parque', 'Almuerzo de campo'],
    excludes: ['Transporte de regreso', 'Equipo de lluvia'],
    searchTerms: [
      'hiking',
      'trail',
      'cloud forest',
      'birds',
      'mountain',
      'river',
      'nature',
      'senderismo',
      'bosque nuboso',
      'quetzal',
    ],
  },
  {
    slug: 'rafting-chiriqui-viejo',
    title: 'Rafting en el río Chiriquí Viejo',
    summary: 'Descenso de clase III entre paredes de bosque, con briefing y práctica de seguridad.',
    destinationName: 'Chiriquí',
    regionId: 'chiriqui',
    categoryName: 'Aventura',
    durationMin: 360,
    priceFrom: 110,
    providerName: 'Operador demo Chiriquí',
    lat: 8.69,
    lng: -82.7,
    includes: ['Equipo completo', 'Guías certificados', 'Almuerzo', 'Transporte local'],
    excludes: ['Fotografías', 'Propinas'],
    searchTerms: [
      'rafting',
      'whitewater',
      'river',
      'rapids',
      'adventure',
      'helmet',
      'water',
      'rafting',
      'río',
      'aventura',
    ],
  },
  {
    slug: 'volcan-baru-noche',
    title: 'Cumbre del Volcán Barú de noche',
    summary:
      'Ascenso nocturno al punto más alto del país para ver los dos océanos al amanecer, si el cielo acompaña.',
    destinationName: 'Volcán Barú',
    regionId: 'chiriqui',
    categoryName: 'Senderismo',
    durationMin: 720,
    priceFrom: 130,
    providerName: 'Operador demo Chiriquí',
    lat: 8.808,
    lng: -82.543,
    includes: ['Guía de montaña', 'Transporte 4x4', 'Refrigerios', 'Entrada al parque'],
    excludes: ['Ropa de abrigo', 'Linterna frontal'],
    searchTerms: [
      'volcano',
      'summit',
      'hiking',
      'sunrise',
      'mountain',
      'night',
      'altitude',
      'volcán',
      'cumbre',
      'amanecer',
    ],
  },
  {
    slug: 'termales-caldera',
    title: 'Aguas termales de Caldera',
    summary: 'Pozas minerales junto al río, con acceso por camino rural y zona de baño natural.',
    destinationName: 'Caldera',
    regionId: 'chiriqui',
    categoryName: 'Bienestar',
    durationMin: 180,
    priceFrom: 40,
    providerName: 'Operador demo Chiriquí',
    lat: 8.66,
    lng: -82.38,
    includes: ['Entrada a las pozas', 'Guía', 'Agua'],
    excludes: ['Transporte', 'Toalla'],
    searchTerms: [
      'hot springs',
      'thermal',
      'river',
      'wellness',
      'relaxation',
      'nature',
      'termales',
      'río',
      'bienestar',
    ],
  },
  {
    slug: 'golfo-chiriqui-isla-gamez',
    title: 'Golfo de Chiriquí: Isla Gámez y snorkel',
    summary:
      'Salida a las islas del parque marino, con arena blanca, agua clara y arrecife accesible desde la playa.',
    destinationName: 'Golfo de Chiriquí',
    regionId: 'chiriqui',
    categoryName: 'Islas',
    durationMin: 480,
    priceFrom: 95,
    providerName: 'Operador demo Chiriquí',
    lat: 8.2,
    lng: -82.2,
    includes: ['Lancha', 'Equipo de snorkel', 'Almuerzo', 'Entrada al parque'],
    excludes: ['Transporte terrestre', 'Bebidas'],
    searchTerms: [
      'island',
      'snorkel',
      'reef',
      'beach',
      'boat',
      'marine park',
      'ocean',
      'isla',
      'arrecife',
      'snorkel',
    ],
  },

  // ------------------------------------------------------------- Bocas del Toro
  {
    slug: 'cayo-zapatilla-cayo-coral',
    title: 'Cayo Zapatilla y Cayo Coral',
    summary:
      'Día de lancha por el parque marino, con arrecife de cayo coral y la playa protegida de Zapatilla.',
    destinationName: 'Bocas del Toro',
    regionId: 'bocas-del-toro',
    categoryName: 'Islas',
    durationMin: 480,
    priceFrom: 85,
    providerName: 'Operador demo Bocas',
    lat: 9.27,
    lng: -82.05,
    includes: ['Lancha', 'Equipo de snorkel', 'Entrada al parque'],
    excludes: ['Almuerzo', 'Bebidas'],
    searchTerms: [
      'island',
      'snorkel',
      'reef',
      'beach',
      'caribbean',
      'boat',
      'marine park',
      'cayo',
      'arrecife',
      'playa',
    ],
  },
  {
    slug: 'delfines-playa-estrella',
    title: 'Delfines de la bahía y Playa Estrella',
    summary:
      'Recorrido por la bahía donde se alimentan los delfines y parada en la playa de las estrellas de mar.',
    destinationName: 'Bocas del Toro',
    regionId: 'bocas-del-toro',
    categoryName: 'Naturaleza',
    durationMin: 420,
    priceFrom: 70,
    providerName: 'Operador demo Bocas',
    lat: 9.34,
    lng: -82.26,
    includes: ['Lancha', 'Guía', 'Chaleco salvavidas'],
    excludes: ['Comidas', 'Propinas'],
    searchTerms: [
      'dolphin',
      'wildlife',
      'boat',
      'bay',
      'starfish',
      'beach',
      'marine',
      'delfines',
      'bahía',
      'estrellas de mar',
    ],
  },
  {
    slug: 'surf-playa-bluff',
    title: 'Surf en Playa Bluff',
    summary: 'Clase en la playa de oleaje fuerte de Isla Colón, con lectura de corrientes y práctica.',
    destinationName: 'Isla Colón',
    regionId: 'bocas-del-toro',
    categoryName: 'Playa y mar',
    durationMin: 180,
    priceFrom: 60,
    providerName: 'Operador demo Bocas',
    lat: 9.37,
    lng: -82.22,
    includes: ['Tabla', 'Licra', 'Instructor'],
    excludes: ['Transporte', 'Bloqueador solar'],
    searchTerms: [
      'surf',
      'waves',
      'beach',
      'board',
      'ocean',
      'caribbean',
      'surfing',
      'olas',
      'tabla',
      'playa',
    ],
  },
  {
    slug: 'manglares-kayak-transparente',
    title: 'Manglares en kayak transparente',
    summary: 'Remada de casco transparente sobre praderas marinas y raíces de manglar.',
    destinationName: 'Bocas del Toro',
    regionId: 'bocas-del-toro',
    categoryName: 'Naturaleza',
    durationMin: 150,
    priceFrom: 55,
    providerName: 'Operador demo Bocas',
    lat: 9.33,
    lng: -82.24,
    includes: ['Kayak transparente', 'Chaleco salvavidas', 'Guía'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'kayak',
      'mangrove',
      'clear',
      'paddling',
      'water',
      'nature',
      'seagrass',
      'kayak',
      'manglar',
      'transparente',
    ],
  },
  {
    slug: 'bastimentos-wizard-beach',
    title: 'Isla Bastimentos y Wizard Beach',
    summary: 'Sendero de selva hasta una playa abierta al Caribe, con parada en el pueblo de Old Bank.',
    destinationName: 'Isla Bastimentos',
    regionId: 'bocas-del-toro',
    categoryName: 'Playa y mar',
    durationMin: 360,
    priceFrom: 65,
    providerName: 'Operador demo Bocas',
    lat: 9.33,
    lng: -82.14,
    includes: ['Taxi marino', 'Guía', 'Agua'],
    excludes: ['Almuerzo', 'Calzado de sendero'],
    searchTerms: [
      'beach',
      'jungle',
      'trail',
      'island',
      'caribbean',
      'hiking',
      'village',
      'playa',
      'selva',
      'sendero',
    ],
  },
  {
    slug: 'buceo-iniciacion-bocas',
    title: 'Buceo de iniciación en el arrecife de Bocas',
    summary:
      'Primera inmersión acompañada en aguas someras, con teoría en superficie y práctica en piscina natural.',
    destinationName: 'Bocas del Toro',
    regionId: 'bocas-del-toro',
    categoryName: 'Buceo',
    durationMin: 300,
    priceFrom: 140,
    providerName: 'Operador demo Bocas',
    lat: 9.335,
    lng: -82.247,
    includes: ['Equipo completo de buceo', 'Instructor certificado', 'Dos inmersiones'],
    excludes: ['Certificación', 'Comidas'],
    searchTerms: [
      'diving',
      'scuba',
      'reef',
      'underwater',
      'ocean',
      'fish',
      'caribbean',
      'buceo',
      'arrecife',
      'inmersión',
    ],
  },

  // ------------------------------------------------------------------ Veraguas
  {
    slug: 'buceo-coiba',
    title: 'Buceo en el Parque Nacional Coiba',
    summary:
      'Dos inmersiones en un parque marino de aguas abiertas, con probabilidad de tiburones de arrecife y tortugas.',
    destinationName: 'Coiba',
    regionId: 'veraguas',
    categoryName: 'Buceo',
    durationMin: 600,
    priceFrom: 195,
    providerName: 'Operador demo Veraguas',
    lat: 7.46,
    lng: -81.75,
    includes: ['Equipo de buceo', 'Dos inmersiones', 'Almuerzo', 'Entrada al parque'],
    excludes: ['Certificación', 'Transporte terrestre'],
    searchTerms: [
      'diving',
      'scuba',
      'national park',
      'shark',
      'turtle',
      'underwater',
      'island',
      'buceo',
      'parque nacional',
      'tortuga',
    ],
  },
  {
    slug: 'santa-catalina-surf',
    title: 'Santa Catalina: surf con instructor',
    summary: 'Clase en una de las rompientes más constantes del Pacífico panameño, para todos los niveles.',
    destinationName: 'Santa Catalina',
    regionId: 'veraguas',
    categoryName: 'Playa y mar',
    durationMin: 180,
    priceFrom: 50,
    providerName: 'Operador demo Veraguas',
    lat: 7.63,
    lng: -81.27,
    includes: ['Tabla', 'Instructor', 'Licra'],
    excludes: ['Transporte', 'Seguro'],
    searchTerms: [
      'surf',
      'waves',
      'point break',
      'beach',
      'ocean',
      'board',
      'pacific',
      'olas',
      'rompiente',
      'surf',
    ],
  },
  {
    slug: 'isla-cebaco-pesca',
    title: 'Isla Cébaco: pesca y playa',
    summary: 'Jornada de pesca costera y fondeo en una ensenada tranquila para comer y nadar.',
    destinationName: 'Isla Cébaco',
    regionId: 'veraguas',
    categoryName: 'Pesca',
    durationMin: 540,
    priceFrom: 160,
    providerName: 'Operador demo Veraguas',
    lat: 7.52,
    lng: -81.18,
    includes: ['Embarcación', 'Equipo de pesca', 'Almuerzo', 'Capitán'],
    excludes: ['Licencia de pesca', 'Bebidas alcohólicas'],
    searchTerms: [
      'fishing',
      'boat',
      'island',
      'ocean',
      'pacific',
      'beach',
      'anchor',
      'pesca',
      'embarcación',
      'isla',
    ],
  },
  {
    slug: 'ballenas-golfo-montijo',
    title: 'Ballenas jorobadas en el Golfo de Montijo',
    summary:
      'Salida de temporada por aguas donde las jorobadas paren y crían, con protocolo de distancia.',
    destinationName: 'Golfo de Montijo',
    regionId: 'veraguas',
    categoryName: 'Naturaleza',
    durationMin: 300,
    priceFrom: 90,
    providerName: 'Operador demo Veraguas',
    lat: 7.7,
    lng: -81.1,
    includes: ['Lancha', 'Guía marino', 'Chaleco salvavidas'],
    excludes: ['Comidas', 'Transporte terrestre'],
    searchTerms: [
      'whale',
      'marine',
      'wildlife',
      'boat',
      'ocean',
      'nature',
      'gulf',
      'ballenas',
      'jorobadas',
      'golfo',
    ],
  },

  // -------------------------------------------------------------------- Azuero
  {
    slug: 'isla-iguana-pedasi',
    title: 'Isla Iguana desde Pedasí',
    summary:
      'Refugio de vida silvestre con arena blanca, colonia de fragatas y arrecife a pocos metros de la orilla.',
    destinationName: 'Pedasí',
    regionId: 'azuero',
    categoryName: 'Islas',
    durationMin: 360,
    priceFrom: 80,
    providerName: 'Operador demo Azuero',
    lat: 7.635,
    lng: -79.9,
    includes: ['Lancha', 'Equipo de snorkel', 'Entrada al refugio'],
    excludes: ['Almuerzo', 'Transporte terrestre'],
    searchTerms: [
      'island',
      'snorkel',
      'reef',
      'beach',
      'birds',
      'wildlife',
      'white sand',
      'isla',
      'refugio',
      'arrecife',
    ],
  },
  {
    slug: 'surf-playa-venao',
    title: 'Clase de surf en Playa Venao',
    summary: 'Bahía en herradura con olas parejas, ideal para una primera clase con instructor.',
    destinationName: 'Playa Venao',
    regionId: 'azuero',
    categoryName: 'Playa y mar',
    durationMin: 180,
    priceFrom: 55,
    providerName: 'Operador demo Azuero',
    lat: 7.43,
    lng: -80.2,
    includes: ['Tabla', 'Licra', 'Instructor certificado'],
    excludes: ['Transporte', 'Bloqueador solar'],
    searchTerms: [
      'surf',
      'waves',
      'beach',
      'bay',
      'board',
      'ocean',
      'beginner',
      'olas',
      'playa',
      'surf',
    ],
  },
  {
    slug: 'artesania-la-arena',
    title: 'Ruta de artesanía y polleras en La Arena',
    summary:
      'Talleres de cerámica al torno y bordado de pollera, con demostración de los oficios que definen la región.',
    destinationName: 'Chitré',
    regionId: 'azuero',
    categoryName: 'Cultura',
    durationMin: 240,
    priceFrom: 40,
    providerName: 'Operador demo Azuero',
    lat: 7.96,
    lng: -80.46,
    includes: ['Visitas a talleres', 'Guía cultural', 'Demostración'],
    excludes: ['Compra de artesanía', 'Comidas'],
    searchTerms: [
      'craft',
      'pottery',
      'textile',
      'culture',
      'tradition',
      'workshop',
      'artesanía',
      'cerámica',
      'pollera',
    ],
  },
  {
    slug: 'cenegon-del-mangle',
    title: 'Refugio de vida silvestre Cenegón del Mangle',
    summary:
      'Pasarela sobre manglar con garzas anidando y pozas de barro termal al final del sendero.',
    destinationName: 'Los Santos',
    regionId: 'azuero',
    categoryName: 'Naturaleza',
    durationMin: 180,
    priceFrom: 35,
    providerName: 'Operador demo Azuero',
    lat: 7.9,
    lng: -80.42,
    includes: ['Entrada al refugio', 'Guía naturalista'],
    excludes: ['Transporte', 'Comidas'],
    searchTerms: [
      'mangrove',
      'birds',
      'wildlife',
      'boardwalk',
      'wetland',
      'nature',
      'mud',
      'manglar',
      'garzas',
      'refugio',
    ],
  },
];

export const demoCatalogVersion = 'demo-seed-pa-2026-09-10-v1';

export const demoTourCatalog: LocalTour[] = localTourSchema.array().parse(
  seeds.map((seed) => ({
    tourRefId: `demo-${seed.slug}`,
    slug: seed.slug,
    title: seed.title,
    summary: seed.summary,
    destinationName: seed.destinationName,
    categoryName: seed.categoryName,
    durationMin: seed.durationMin,
    includes: seed.includes,
    excludes: seed.excludes,
    searchTerms: seed.searchTerms,
    source: 'demo-seed',
    regionId: seed.regionId,
    geo: { lat: seed.lat, lng: seed.lng },
    priceFrom: seed.priceFrom,
    currency: demoCurrency,
    providerName: seed.providerName,
  })),
);
